### ISSUE TITLE
Parenthesis oddly colored if chained.

### ISSUE THREAD

**Issue by RobMayer** [AndrewLeedham/vscode-modular-css#49]
```
.dateselect_dropdown:global(.state_open) {
/*open parens after global will be colored as "global" */
}

:global(.state_focus).dateselect_dropdown {
/* open parens after global will be uncolored */
}
```

**Comment by AndrewLeedham** [comment]
Can you provide a screenshot of what you mean, I am seeing the following:
![image](https://user-images.githubusercontent.com/5557458/63591320-4edf2280-c5a6-11e9-9f1f-34548e2dc732.png)

Also what themes/plugins are you using?

**Comment by RobMayer** [comment]
I think it may actually be my theme, not you - sorry to waste your time, but for the sake of understanding:

![image](https://user-images.githubusercontent.com/5171361/63599663-09aff600-c590-11e9-8f64-f583eab9a554.png)

Atom Icons v1.0.2
Babel Javascript
Better Comments
ESLint
Git Graph
(this)
Stylelint-plus
toggle quoets
Yi Dark & Yi Light Themes

**Comment by AndrewLeedham** [comment]
No worries, it does seem like an issue with Yi Dark & Light Themes. The issue occurs without this plugin installed.
